# Generated by Django 4.2.25 on 2025-10-28 20:52

import biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_remove_lector_digito_verificador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='id_comuna',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='lector',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=None, validators=[biblioteca.models.validar_mayoria_edad]),
        ),
        migrations.AlterField(
            model_name='lector',
            name='rut_lector',
            field=models.CharField(max_length=12, unique=True, validators=[biblioteca.models.validar_rut]),
        ),
    ]
