# Generated by Django 4.2.25 on 2025-10-28 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_direccion_id_comuna_alter_lector_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='nacionalidad',
            new_name='id_nacionalidad',
        ),
        migrations.RenameField(
            model_name='biblioteca',
            old_name='direccion',
            new_name='id_direccion',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='tipo_categoria',
            new_name='id_tipo_categoria',
        ),
        migrations.RenameField(
            model_name='lector',
            old_name='biblioteca',
            new_name='id_biblioteca',
        ),
        migrations.RenameField(
            model_name='lector',
            old_name='direccion',
            new_name='id_direccion',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='biblioteca',
            new_name='id_biblioteca',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='categoria',
            new_name='id_categoria',
        ),
        migrations.RenameField(
            model_name='parametro',
            old_name='tipo_parametro',
            new_name='id_tipo_parametro',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='lector',
            new_name='id_lector',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='libro',
            new_name='id_libro',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='comuna',
        ),
        migrations.AlterField(
            model_name='direccion',
            name='id_comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.comuna'),
        ),
    ]
