# Generated by Django 5.2.7 on 2025-11-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_rename_nacionalidad_autor_id_nacionalidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='imagen_autor',
            field=models.URLField(blank=True),
        ),
    ]
