# Generated by Django 5.2.7 on 2025-11-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_alter_comuna_codigo_comuna_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tipo_reserva',
            field=models.IntegerField(choices=[(0, 'Sin Reserva'), (1, '1 Semana'), (2, '1 Mes'), (3, '1 Semestre')], default=0),
        ),
    ]
