# Generated by Django 5.2.7 on 2025-11-18 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0013_autor_genero_lector_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='id_nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.nacionalidad'),
        ),
    ]
